import React from 'react';
import logo from './logo.svg';
import './App.css';

function SP500() {

  return (
    <div className="SP500">
      <header>
        <p>
        <h1>
        S&P 500 Total Returns
        </h1>
        <p>The total returns of the S&P 500 index are listed by year. Total returns include two components: the return generated by dividends and the return generated by price changes in the index. While most individuals focus only on the price returns of the index, dividends play an important factor in overall investment returns.</p>
          <table>
            <tr>
              <th>Year</th>
              <th>Total Return</th>
              <th>Cumulative Returns</th>
            </tr>
            <tr>
              <td>Jill</td>
              <td>Smith</td>
              <td>50</td>
            </tr>
            <tr>
              <td>Eve</td>
              <td>Jackson</td>
              <td>94</td>
            </tr>
          </table>
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Hi bb how are you?!!??!!
        </a>
      </header>
    </div>
  );
}

export default SP500;
